FROM ubuntu:22.04

RUN apt-get update

RUN apt-get -y upgrade

# ADA DEPENDENCIES

RUN apt-get -y install libglew-dev

RUN apt-get -y install libglu1-mesa-dev

RUN apt-get -y install libsqlite3-dev

RUN apt-get -y install libx11-dev

RUN apt-get -y install libgl-dev

RUN apt-get -y install pkg-config

RUN apt-get -y install libopencv-dev

RUN apt-get -y install libeigen3-dev

RUN apt-get -y install libc6-dev

RUN apt-get -y install libspdlog-dev

RUN apt-get -y install libboost-all-dev

RUN apt-get -y install git

RUN apt-get -y install cmake

RUN apt-get -y install cmake-data

RUN apt-get -y install  libglib2.0-dev

RUN apt-get -y install libgstreamer1.0-dev

RUN apt-get -y install libgstreamer-plugins-base1.0-dev

# RUN apt-get -y install git

# RUN apt-get -y install build-essential

# RUN apt-get -y install vim

# RUN apt-get -y install python3

# RUN apt-get -y install python3-dev

# RUN apt-get -y install python3-pip

# RUN apt-get -y install libtool

# RUN apt-get -y install libtool-bin

# RUN apt-get -y install autoconf

# RUN apt-get -y install automake

# RUN apt-get -y install libpugixml-dev

# RUN apt-get -y install pugixml-doc

# RUN apt-get -y install libgtest-dev #GoogleTest

# RUN apt-get -y install libblis-pthread-dev #PThread

# RUN apt-get -y install doxygen

# RUN pip install numpy

# RUN pip install tensorflow

# RUN pip install scipy

# RUN pip install h5py

# ENV DEBIAN_FRONTEND=noninteractive

# RUN apt-get update && apt-get install -y --no-install-recommends openmpi-bin && apt-get install -y --no-install-recommends openmpi-common #OpenMPI

# RUN apt-get install -y --no-install-recommends libopenmpi-dev #OpenMPI

# RUN apt-get install -y --no-install-recommends cmake

# RUN apt-get install -y --no-install-recommends libomp-dev #OpenMP

# RUN apt-get install -y --no-install-recommends mpich #MPI

# RUN apt-get -y --no-install-recommends install gdb

# COPY .vimrc /root/.vimrc 